#!/bin/sh
MYTEX=${HOME}/lib/tex
TEXINPUTS='.//:$TEXMF/tex//':${MYTEX}//
MFINPUTS='.//:$TEXMF/mf//':${MYTEX}//
TFMFONTS='.//:$TEXMF/fonts//':${MYTEX}//

export TEXINPUTS
export MFINPUTS
export TFMFONTS

dvips -D600 "$@"
